### Spring properties
# Service registers under this name
spring:
  application:
    name: zuul-proxy
    

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
      
      
# HTTP Server (Tomcat) Port
server: 
  port: 9898


zuul:
   routes:
          producerservice:
              path: /producer/**
              service-id : profiles-microservice-producer
          consumerservice: 
              path: /consumer/**
              service-id : profiles-microservice-consumer
              
              
          
          

          
